"""The Witness — real-time capture layer for the fossil record.

Generates git post-commit hook scripts, records individual witnessed commits,
installs hooks across the workspace, and reports witness coverage status.
"""

from __future__ import annotations

import subprocess
from datetime import datetime
from pathlib import Path

from organvm_engine.fossil.classifier import classify_commit
from organvm_engine.fossil.epochs import assign_epoch
from organvm_engine.fossil.excavator import detect_organ_from_path, parse_commit_type, parse_numstat
from organvm_engine.fossil.stratum import (
    FossilRecord,
    Provenance,
    compute_record_hash,
    deserialize_record,
    serialize_record,
)

# Marker comment used to detect our hook in existing post-commit scripts
_HOOK_MARKER = "# organvm-fossil-witness"


def generate_hook_script(fossil_record_path: Path, workspace_root: Path) -> str:
    """Generate a shell script for .git/hooks/post-commit.

    The script extracts commit metadata from git log and invokes the
    organvm CLI to record the witnessed commit. Designed to run in < 100ms.

    Args:
        fossil_record_path: Path to the fossil-record.jsonl file.
        workspace_root: Workspace root directory.

    Returns:
        Shell script as a string.
    """
    return f"""\
#!/usr/bin/env bash
set -euo pipefail
{_HOOK_MARKER}
# Lightweight hook — invokes organvm fossil witness record
# Generated by organvm fossil witness install

REPO_PATH="$(git rev-parse --show-toplevel)"

# Extract latest commit metadata
SHA="$(git log -1 --format=%H)"
AUTHOR="$(git log -1 --format=%an)"
DATE="$(git log -1 --format=%aI)"
MESSAGE="$(git log -1 --format=%s)"

# Record the witnessed commit (fire-and-forget to keep hook fast)
organvm fossil witness record \\
    --repo-path "$REPO_PATH" \\
    --workspace "{workspace_root}" \\
    --fossil-path "{fossil_record_path}" \\
    >/dev/null 2>&1 &
"""


def record_witnessed_commit(
    repo_path: Path,
    workspace_root: Path,
    fossil_path: Path,
) -> FossilRecord | None:
    """Record the latest commit in a repo as a witnessed fossil record.

    Reads the latest commit from git log, classifies it, assigns an epoch,
    creates a FossilRecord with WITNESSED provenance, and appends to
    the fossil-record.jsonl file with proper hash-linking.

    Args:
        repo_path: Path to the git repository.
        workspace_root: Workspace root directory.
        fossil_path: Path to the fossil-record.jsonl file.

    Returns:
        The created FossilRecord, or None on failure.
    """
    if not repo_path.is_dir():
        return None

    # Read latest commit
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%H|%aI|%an|%s"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None

    line = result.stdout.strip()
    if not line:
        return None

    parts = line.split("|", 3)
    if len(parts) < 4:
        return None

    sha, ts_raw, author, message = parts

    try:
        timestamp = datetime.fromisoformat(ts_raw)
    except ValueError:
        return None

    # Get numstat for the commit
    numstat_output = ""
    try:
        diff_result = subprocess.run(
            ["git", "diff", "--numstat", f"{sha}^..{sha}"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=True,
        )
        numstat_output = diff_result.stdout
    except subprocess.CalledProcessError:
        # First commit has no parent
        try:
            diff_result = subprocess.run(
                ["git", "diff", "--numstat", sha],
                cwd=repo_path,
                capture_output=True,
                text=True,
                check=False,
            )
            numstat_output = diff_result.stdout
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass

    files_changed, insertions, deletions = parse_numstat(numstat_output)
    repo_name = repo_path.name
    organ = detect_organ_from_path(repo_path, workspace_root)
    conventional_type = parse_commit_type(message)
    archetypes = classify_commit(message, conventional_type, repo_name, organ)
    epoch_obj = assign_epoch(timestamp)
    epoch_id = epoch_obj.id if epoch_obj is not None else None

    # Read last record hash for chain linking
    prev_hash = _read_last_hash(fossil_path)

    record = FossilRecord(
        commit_sha=sha,
        timestamp=timestamp,
        author=author,
        organ=organ,
        repo=repo_name,
        message=message,
        conventional_type=conventional_type,
        files_changed=files_changed,
        insertions=insertions,
        deletions=deletions,
        archetypes=archetypes,
        provenance=Provenance.WITNESSED,
        session_id=None,
        epoch=epoch_id,
        tags=[],
        prev_hash=prev_hash,
    )

    # Append to fossil record
    fossil_path.parent.mkdir(parents=True, exist_ok=True)
    with fossil_path.open("a") as fh:
        fh.write(serialize_record(record) + "\n")

    return record


def _read_last_hash(fossil_path: Path) -> str:
    """Read the hash of the last record in the fossil file for chain linking."""
    if not fossil_path.exists():
        return ""

    last_line = ""
    try:
        with fossil_path.open() as fh:
            for line in fh:
                stripped = line.strip()
                if stripped:
                    last_line = stripped
    except OSError:
        return ""

    if not last_line:
        return ""

    try:
        last_record = deserialize_record(last_line)
        return compute_record_hash(last_record)
    except Exception:
        return ""


def install_hooks(
    workspace_root: Path,
    fossil_path: Path,
    dry_run: bool = True,
) -> list[Path]:
    """Install post-commit hooks across all git repos in the workspace.

    Finds all .git directories under workspace_root and generates a
    post-commit hook script for each. Respects existing hooks by
    appending rather than overwriting.

    Args:
        workspace_root: Workspace root directory.
        fossil_path: Path to the fossil-record.jsonl file.
        dry_run: If True (default), report what would be done without writing.

    Returns:
        List of paths where hooks were (or would be) installed.
    """
    repos = _find_git_repos(workspace_root)
    script = generate_hook_script(fossil_path, workspace_root)
    installed: list[Path] = []

    for repo_path in sorted(repos):
        hook_path = repo_path / ".git" / "hooks" / "post-commit"
        installed.append(hook_path)

        if dry_run:
            continue

        hook_path.parent.mkdir(parents=True, exist_ok=True)

        if hook_path.exists():
            existing = hook_path.read_text()
            if _HOOK_MARKER in existing:
                # Already installed, skip
                continue
            # Append to existing hook
            with hook_path.open("a") as fh:
                fh.write("\n" + script)
        else:
            hook_path.write_text(script)

        # Ensure executable
        hook_path.chmod(0o755)

    return installed


def witness_status(workspace_root: Path) -> dict:
    """Scan all repos for installed witness hooks.

    Args:
        workspace_root: Workspace root directory.

    Returns:
        Dict with total_repos, witnessed, dark counts and per-repo details.
    """
    repos = _find_git_repos(workspace_root)
    witnessed = 0
    dark = 0
    repo_details: list[dict] = []

    for repo_path in sorted(repos):
        hook_path = repo_path / ".git" / "hooks" / "post-commit"
        has_hook = False
        if hook_path.exists():
            try:
                content = hook_path.read_text()
                has_hook = _HOOK_MARKER in content
            except OSError:
                pass

        if has_hook:
            witnessed += 1
        else:
            dark += 1

        repo_details.append({
            "path": str(repo_path),
            "name": repo_path.name,
            "witnessed": has_hook,
        })

    return {
        "total_repos": len(repos),
        "witnessed": witnessed,
        "dark": dark,
        "repos": repo_details,
    }


def _find_git_repos(workspace_root: Path) -> list[Path]:
    """Find all git repos under workspace_root (up to depth 4)."""
    repos: list[Path] = []
    if not workspace_root.is_dir():
        return repos

    try:
        for candidate in workspace_root.rglob(".git"):
            try:
                rel = candidate.relative_to(workspace_root)
            except ValueError:
                continue
            if len(rel.parts) <= 5 and candidate.is_dir():
                repos.append(candidate.parent)
    except OSError:
        pass

    return repos
