"""Narrative testament synthesis from ledger + map state.

Generates periodic narratives that synthesize what connections
were made, which lenses were active, and what patterns emerged.
The narrative layer of the testament.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from organvm_engine.network.ledger import read_ledger
from organvm_engine.network.mapper import discover_network_maps
from organvm_engine.network.metrics import (
    convergence_points,
    engagement_velocity,
    form_balance,
    lens_balance,
    mirror_coverage,
    network_density,
    network_reciprocity,
)
from organvm_engine.network.schema import EngagementEntry


def _period_filter(entries: list[EngagementEntry], period: str) -> list[EngagementEntry]:
    """Filter ledger entries by period."""
    if period == "all-time":
        return entries

    # Period filtering placeholder — refined in full implementation
    # For now, return all entries
    return entries


def synthesize_testament(
    workspace: Path,
    ledger_path: Path | None = None,
    period: str = "monthly",
    total_active_repos: int = 0,
) -> str:
    """Generate a narrative testament synthesis.

    Args:
        workspace: Workspace root for discovering network maps.
        ledger_path: Path to engagement ledger.
        period: "weekly", "monthly", or "all-time".
        total_active_repos: Total active repos for density calculation.

    Returns:
        Markdown narrative suitable for praxis-perpetua/testament/.
    """
    # Gather data
    map_pairs = discover_network_maps(workspace)
    maps = [nmap for _, nmap in map_pairs]
    entries = _period_filter(read_ledger(ledger_path), period)

    # Compute metrics
    density = network_density(maps, total_active_repos) if total_active_repos else 0.0
    coverage = mirror_coverage(maps)
    velocity = engagement_velocity(entries, 30 if period == "monthly" else 7)
    reciprocity = network_reciprocity(entries)
    lenses = lens_balance(entries)
    forms = form_balance(entries)
    convergences = convergence_points(maps)

    # Build narrative
    now = datetime.now(timezone.utc)
    lines: list[str] = []
    lines.append(f"# Network Testament — {period.title()} Synthesis")
    lines.append(f"\n**Period:** {period} ending {now.strftime('%Y-%m-%d')}")
    lines.append(f"**Generated:** {now.isoformat()}")
    lines.append("")

    # State of the map
    lines.append("## Mirror Coverage")
    lines.append("")
    lines.append(f"- **Network density:** {density:.1%} of active repos mapped")
    lines.append(f"- **Technical mirrors:** {coverage['technical']:.1%} of mapped repos")
    lines.append(f"- **Parallel mirrors:** {coverage['parallel']:.1%} of mapped repos")
    lines.append(f"- **Kinship mirrors:** {coverage['kinship']:.1%} of mapped repos")
    lines.append(f"- **Total maps:** {len(maps)} repos with network-map.yaml")
    lines.append(f"- **Total mirrors:** {sum(m.mirror_count for m in maps)}")
    lines.append("")

    # Engagement summary
    lines.append("## Engagement")
    lines.append("")
    if entries:
        lines.append(f"- **Actions this period:** {len(entries)}")
        lines.append(f"- **Velocity:** {velocity:.1f} actions/day")
        lines.append(f"- **Reciprocity:** {reciprocity:.1%} received response")
        lines.append("")
        lines.append("### By Lens")
        for lens_name, ratio in sorted(lenses.items(), key=lambda x: -x[1]):
            count = sum(1 for e in entries if e.lens == lens_name)
            lines.append(f"- {lens_name}: {count} ({ratio:.0%})")
        lines.append("")
        lines.append("### By Form")
        for form_name, ratio in sorted(forms.items(), key=lambda x: -x[1]):
            count = sum(1 for e in entries if e.action_type == form_name)
            lines.append(f"- {form_name}: {count} ({ratio:.0%})")
    else:
        lines.append("*No engagement actions recorded this period.*")
    lines.append("")

    # Convergence points
    if convergences:
        lines.append("## Convergence Points")
        lines.append("")
        lines.append("External projects mirrored by multiple ORGANVM repos:")
        lines.append("")
        for project, repos in sorted(convergences.items(), key=lambda x: -len(x[1])):
            lines.append(f"- **{project}** ← {', '.join(repos)}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by `organvm network synthesize`. The Mirror Protocol.*")

    return "\n".join(lines)


def write_testament(
    content: str,
    testament_dir: Path,
    period: str = "monthly",
) -> Path:
    """Write testament narrative to the testament directory.

    Args:
        content: The markdown narrative.
        testament_dir: Path to praxis-perpetua/testament/.
        period: Used for filename.

    Returns:
        Path to the written file.
    """
    now = datetime.now(timezone.utc)
    filename = f"{now.strftime('%Y-%m-%d')}-network-synthesis.md"
    out_path = testament_dir / filename
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    return out_path
