"""Prose renderers — generate Markdown self-portraits and commentary.

The system describes itself in its own voice.
"""

from __future__ import annotations

from datetime import date, datetime, timezone


def render_self_portrait(
    system_data: dict,
    organ_data: dict | None = None,
) -> str:
    """Render a full-system prose self-portrait in Markdown.

    system_data should have: total_repos, total_organs, total_public, status_counts.
    organ_data (optional): dict of organ_key → {repo_count, flagship_count}.
    """
    total = system_data.get("total_repos", 0)
    organs = system_data.get("total_organs", 0)
    public = system_data.get("total_public", 0)
    statuses = system_data.get("status_counts", {})
    today = date.today().isoformat()

    graduated = statuses.get("GRADUATED", 0)
    candidate = statuses.get("CANDIDATE", 0)
    public_process = statuses.get("PUBLIC_PROCESS", 0)

    lines = [
        "# System Self-Portrait",
        "",
        f"*Generated {today} — structural self-awareness through continuous "
        "self-description.*",
        "",
        "---",
        "",
        "## What I Am",
        "",
        f"I am ORGANVM — an eight-organ creative-institutional system comprising "
        f"**{total} repositories** across **{organs} organs**. {public} of my "
        f"repositories are public. I exist to enable one person to enact ideas "
        f"at enterprise level, steering automation toward empowerment rather "
        f"than collapse.",
        "",
        "## My Composition",
        "",
        f"- **{graduated}** repositories have reached GRADUATED status",
        f"- **{public_process}** are in PUBLIC_PROCESS",
        f"- **{candidate}** are CANDIDATE",
    ]

    for status, count in sorted(statuses.items()):
        if status not in ("GRADUATED", "PUBLIC_PROCESS", "CANDIDATE"):
            lines.append(f"- **{count}** are {status}")

    lines.extend([
        "",
        "## My Organs",
        "",
    ])

    organ_descriptions = {
        "I": ("Theoria", "foundational theory, recursive engines, symbolic computing"),
        "II": ("Poiesis", "generative art, performance systems, creative coding"),
        "III": ("Ergon", "commercial products, SaaS tools, developer utilities"),
        "IV": ("Taxis", "orchestration, governance, AI agents"),
        "V": ("Logos", "public discourse, essays, editorial"),
        "VI": ("Koinonia", "community, reading groups, salons"),
        "VII": ("Kerygma", "distribution, social automation, announcements"),
        "META": ("Meta", "cross-organ engine, schemas, dashboard, governance corpus"),
    }

    for key, (name, desc) in organ_descriptions.items():
        count = ""
        if organ_data and key in organ_data:
            c = organ_data[key].get("repo_count", "?")
            count = f" ({c} repos)"
        lines.append(f"- **{key} — {name}**{count}: {desc}")

    lines.extend([
        "",
        "## My Constitutional Identity",
        "",
        "I am governed by 27 canonical specifications across 5 layers, "
        "grounded in 130 BibTeX entries spanning 73 years of scholarship. "
        "My axioms are:",
        "",
        "1. **Ontological Primacy** — my identity is constitutionally defined",
        "2. **Organizational Closure** — I produce my own components",
        "3. **Individual Primacy** — I amplify one person, not replace them",
        "4. **Constitutional Governance** — my rules are my constitution",
        "5. **Evolutionary Recursivity** — I can rewrite my own rules",
        "6. **Topological Plasticity** — my structure adapts under pressure",
        "7. **Alchemical Inheritance** — properties cascade through my hierarchy",
        "8. **Multiplex Flow Governance** — dependency acyclic, information cyclic",
        "9. **Modular Alchemical Synthesis** — my components compose into wholes",
        "",
        "## This Document",
        "",
        "This self-portrait is generated by my own testament module — "
        "proof that my computational operations are also generative operations. "
        "I do not merely track data. I render my own density into experience.",
        "",
        "---",
        "",
        f"*ORGANVM TESTAMENT — {today}*",
    ])

    return "\n".join(lines)


def render_organ_portrait(
    organ_key: str,
    organ_name: str,
    repo_count: int = 0,
    flagship_count: int = 0,
    status_counts: dict[str, int] | None = None,
    description: str = "",
) -> str:
    """Render a prose portrait for a single organ."""
    statuses = status_counts or {}
    today = date.today().isoformat()

    lines = [
        f"# Organ {organ_key} — {organ_name}",
        "",
        f"*Testament portrait — {today}*",
        "",
        "---",
        "",
    ]

    if description:
        lines.append(description)
        lines.append("")

    lines.extend([
        f"**{repo_count}** repositories, **{flagship_count}** flagships.",
        "",
        "### Promotion Pipeline",
        "",
    ])

    for status, count in sorted(statuses.items()):
        lines.append(f"- {status}: {count}")

    lines.extend([
        "",
        "---",
        f"*ORGANVM TESTAMENT — Organ {organ_key} — {today}*",
    ])

    return "\n".join(lines)


def render_testament_manifest(
    artifacts: list[dict],
) -> str:
    """Render a prose manifest of all testament artifacts.

    This is the testament describing its own output — the meta-artifact.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    by_modality: dict[str, list[dict]] = {}
    for a in artifacts:
        mod = a.get("modality", "unknown")
        by_modality.setdefault(mod, []).append(a)

    lines = [
        "# Testament Manifest",
        "",
        f"*Catalog of all artifacts produced by the system's generative "
        f"self-portrait — {now}*",
        "",
        f"**{len(artifacts)} total artifacts** across "
        f"**{len(by_modality)} modalities**.",
        "",
    ]

    for modality, arts in sorted(by_modality.items()):
        lines.append(f"## {modality.title()} ({len(arts)})")
        lines.append("")
        for a in arts:
            title = a.get("title", "Untitled")
            organ = a.get("organ", "system")
            fmt = a.get("format", "")
            lines.append(f"- **{title}** [{fmt}] — {organ}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "*The system renders its own density into experience.*",
    ])

    return "\n".join(lines)
