"""Advisory system — governance recommendations from policy evaluation.

Advisories are generated by evaluating ontologia governance policies
against live system state.  Each advisory is a structured recommendation
that can be acknowledged, dismissed, or acted upon.

Storage: ~/.organvm/advisories.jsonl (append-only)
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _advisories_path() -> Path:
    return Path.home() / ".organvm" / "advisories.jsonl"


@dataclass
class Advisory:
    """A governance recommendation generated by policy evaluation."""

    advisory_id: str
    policy_id: str
    action: str
    entity_id: str
    entity_name: str
    description: str
    severity: str  # "info" / "warning" / "critical"
    timestamp: str
    evidence: dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Advisory:
        return cls(
            advisory_id=data.get("advisory_id", ""),
            policy_id=data.get("policy_id", ""),
            action=data.get("action", ""),
            entity_id=data.get("entity_id", ""),
            entity_name=data.get("entity_name", ""),
            description=data.get("description", ""),
            severity=data.get("severity", "info"),
            timestamp=data.get("timestamp", ""),
            evidence=data.get("evidence", {}),
            acknowledged=data.get("acknowledged", False),
        )


def _make_advisory_id(policy_id: str, entity_id: str) -> str:
    """Deterministic advisory ID from policy + entity for deduplication."""
    raw = f"{policy_id}:{entity_id}"
    return hashlib.sha256(raw.encode()).hexdigest()[:12]


def _severity_from_action(action: str) -> str:
    """Map policy action to severity level."""
    critical = {"flag", "deprecate"}
    warning = {"promote", "merge", "notify"}
    if action in critical:
        return "critical" if action == "deprecate" else "warning"
    if action in warning:
        return "info"
    return "info"


def _build_repo_state(repo_dict: dict[str, Any]) -> dict[str, Any]:
    """Build entity state dict from registry repo data for policy evaluation."""
    last_val = repo_dict.get("last_validated", "")
    is_stale = False
    if last_val:
        try:
            val_dt = datetime.fromisoformat(last_val)
            is_stale = (datetime.now(timezone.utc) - val_dt) > timedelta(days=30)
        except (ValueError, TypeError):
            pass

    return {
        "promotion_status": repo_dict.get("promotion_status", ""),
        "ci_workflow": bool(repo_dict.get("ci_workflow")),
        "platinum_status": bool(repo_dict.get("platinum_status")),
        "implementation_status": repo_dict.get("implementation_status", ""),
        "is_stale": is_stale,
        "last_validated": last_val,
        "lifecycle": "ACTIVE",
        # Fields checked by non-repo-scoped policies — safe defaults
        "is_orphan": False,
        "incoming_relations": 0,
        "cluster_size": 0,
        "cohesion": 0.0,
        "has_active_dependents": False,
    }


def evaluate_all_policies(workspace: Path | None = None) -> list[Advisory]:
    """Evaluate default policies against live registry state.

    Returns a list of new advisories (deduplicates against existing ones).
    """
    from organvm_engine.pulse.default_policies import DEFAULT_POLICIES

    if not DEFAULT_POLICIES:
        return []

    try:
        from organvm_engine.registry.loader import load_registry
    except ImportError:
        return []

    try:
        registry = load_registry()
    except Exception:
        logger.debug("Could not load registry for policy evaluation", exc_info=True)
        return []

    # Read existing advisory IDs for deduplication
    existing_ids = {a.advisory_id for a in read_advisories(limit=500)}

    now = datetime.now(timezone.utc).isoformat()
    advisories: list[Advisory] = []

    # Evaluate per-repo policies
    for organ_key, organ_data in registry.get("organs", {}).items():
        for repo in organ_data.get("repositories", []):
            repo_name = repo.get("name", "")
            entity_id = f"{organ_key}/{repo_name}"
            state = _build_repo_state(repo)

            for policy in DEFAULT_POLICIES:
                if policy.scope_entity_type and policy.scope_entity_type != "repo":
                    continue
                if policy.evaluate(state):
                    adv_id = _make_advisory_id(policy.policy_id, entity_id)
                    if adv_id in existing_ids:
                        continue
                    advisories.append(Advisory(
                        advisory_id=adv_id,
                        policy_id=policy.policy_id,
                        action=policy.action.value,
                        entity_id=entity_id,
                        entity_name=repo_name,
                        description=f"{policy.name}: {repo_name}",
                        severity=_severity_from_action(policy.action.value),
                        timestamp=now,
                        evidence={k: v for k, v in state.items()
                                  if v and v is not True},
                    ))

    return advisories


def store_advisories(advisories: list[Advisory]) -> None:
    """Append advisories to ~/.organvm/advisories.jsonl."""
    if not advisories:
        return
    path = _advisories_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as f:
        for adv in advisories:
            f.write(json.dumps(adv.to_dict(), separators=(",", ":"), default=str) + "\n")


def read_advisories(
    limit: int = 50,
    unacked_only: bool = False,
) -> list[Advisory]:
    """Read recent advisories from the JSONL store."""
    path = _advisories_path()
    if not path.is_file():
        return []

    advisories: list[Advisory] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            adv = Advisory.from_dict(json.loads(line))
            if unacked_only and adv.acknowledged:
                continue
            advisories.append(adv)
        except (json.JSONDecodeError, TypeError):
            continue

    return advisories[-limit:]


def acknowledge_advisory(advisory_id: str) -> bool:
    """Mark an advisory as acknowledged by rewriting the JSONL.

    Returns True if the advisory was found and updated.
    """
    path = _advisories_path()
    if not path.is_file():
        return False

    lines = path.read_text().splitlines()
    found = False
    new_lines: list[str] = []

    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            data = json.loads(line)
            if data.get("advisory_id") == advisory_id:
                data["acknowledged"] = True
                found = True
            new_lines.append(json.dumps(data, separators=(",", ":"), default=str))
        except (json.JSONDecodeError, TypeError):
            new_lines.append(line)

    if found:
        path.write_text("\n".join(new_lines) + "\n" if new_lines else "")

    return found
